---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fcdemo-agent-app
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: fcdemo-agent-app
    spec:
      containers:
      - name: fcdemo-agent-app
        image: mcas/franceconnect-agent-demo:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fcdemo-agent-service
  labels:
    app: fcdemo-agent-service
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on Kubernetes
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: fcdemo-agent-app
